version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - rangerrick
  labels:
  - dependabot
  ignore:
  - dependency-name: angular-ui-router
    versions:
    - "> 0.2.18"
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: cordova-res
    versions:
    - 0.15.2
  - dependency-name: cordova-ios
    versions:
    - 6.1.1
  - dependency-name: cordova-android
    versions:
    - 9.0.0
  commit-message:
    prefix: build
    include: scope
