notifications:
  irc:
    - "chat.freenode.net#cruisemonkey"
language: node_js
node_js:
  - 'node'
before_install:
  - 'npm install -g ionic cordova bower webpack webpack-cli mocha'
  - 'npm install'
  - 'bower install'
  - 'npm run setup'
script: npm test
cache:
  directories:
    - node_modules
    - app/bower_components

