language: node_js
node_js:
  - '0.10'
  - '0.11'
services:
  - couchdb
before_install:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - 'gem install compass'
  - 'sudo pip install couchapp'
before_script:
  - cd couchdb; couchapp push http://localhost:5984/test-pristine
