notifications:
  irc:
    - "chat.freenode.net#cruisemonkey"
language: node_js
node_js:
  - '4.2'
before_install:
  - 'npm install -g ionic cordova bower webpack webpack-cli karma-cli'
  - 'npm install'
  - 'bower install'
script: npm test
cache:
  directories:
    - node_modules
    - bower_components
