notifications:
  irc:
    - "chat.freenode.net#cruisemonkey"
language: node_js
node_js:
  - '4.1'
#services:
#  - couchdb
before_install:
  - 'npm install -g webpack-cli bower karma-cli'
  - 'npm install'
  - 'bower install'
#before_script:
#  - './setup-travis.sh'
#script: npm run test
cache:
  directories:
    - node_modules
    - bower_components
