notifications:
  irc:
    - "chat.freenode.net#cruisemonkey"
language: node_js
node_js:
  - 'node'
before_install:
  - 'npm install -g ionic bower'
  - 'npm install'
script: npm test
cache:
  directories:
    - node_modules
    - app/bower_components

