notifications:
  irc:
    - "chat.freenode.net#cruisemonkey"
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
before_script:
  - './bin/clean.sh'
before_install:
  - 'npm install -g ionic cordova bower webpack webpack-cli mocha'
  - 'npm install'
  - 'bower install'
script: npm test
cache:
  directories:
    - node_modules
    - app/bower_components

