# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CruiseMonkey Blog
email: cruisemonkey@raccoonfink.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rangerrick.github.io/CruiseMonkey/" # the base hostname & protocol for your site
twitter_username: rangerrick
github_username: rangerrick

# Build settings
markdown: kramdown
